apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skyadmin-agent.fullname" . }}
  labels:
    {{- include "skyadmin-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "skyadmin-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "skyadmin-agent.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "skyadmin-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # Configuration from values
            - name: API_TOKEN
              value: {{ .Values.config.apiToken | quote }}
            - name: VLAN
              value: {{ .Values.config.vlan | quote }}
            - name: MAC_ADDRESS
              value: {{ .Values.config.macAddress | quote }}
            - name: IP_ADDRESS
              value: {{ .Values.config.ipAddress | quote }}
            - name: NSEID
              value: {{ .Values.config.nseid | quote }}
            - name: LASTNAME
              value: {{ .Values.config.lastName | quote }}
            - name: ROOMNUMBER
              value: {{ .Values.config.roomNumber | quote }}
            - name: PROPERTYID
              value: {{ .Values.config.propertyId | quote }}
            - name: REGMETHODID
              value: {{ .Values.config.registrationMethodId | quote }}
            - name: RATEPLANID
              value: {{ .Values.config.ratePlanId | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel | quote }}
            # Additional environment variables
            {{- range .Values.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
