name: Build and Publish Container

on:
  push:
    paths:
      - "main.go"
      - "Dockerfile"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/skyportal

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate variables
        id: vars
        run: |
          echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            --tag $IMAGE_NAME:$DATE \
            --tag $IMAGE_NAME:latest \
            .

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$DATE
          docker push $IMAGE_NAME:latest
