name: Build and Publish Container

on:
  push:
    paths:
      - "main.go"
      - "Dockerfile"
    tags:
      - "v*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate variables
        id: vars
        run: |
          echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

          # Extract version from git tag or use 'dev' for non-tag builds
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="dev-$(git rev-parse --short HEAD)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        run: |
          # Build image with version information embedded via ldflags
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=$VERSION \
            --tag $IMAGE_NAME:$VERSION \
            --tag $IMAGE_NAME:latest \
            --push \
            .
